<?php defined( 'ABSPATH' ) OR die( 'This script cannot be accessed directly.' );

/**
 * Shortcode: us_gmaps
 *
 * @var $shortcode string Current shortcode name
 * @var $config array Shortcode's config
 *
 * @param $config ['atts'] array Shortcode's attributes and default values
 */
vc_map( array(
	'base' => 'us_gmaps',
	'name' => __( 'Google Maps', 'us' ),
	'icon' => 'icon-wpb-map-pin',
	'category' => __( 'Content', 'us' ),
	'weight' => 160,
	'params' => array(
		array(
			'param_name' => 'marker_address',
			'heading' => __( 'Address', 'us' ),
			'description' => '',
			'type' => 'textfield',
			'std' => $config['atts']['marker_address'],
			'holder' => 'div',
			'weight' => 190,
		),
		array(
			'param_name' => 'marker_text',
			'heading' => __( 'Marker Text', 'us' ),
			'description' => __( 'Enter your content, HTML tags are allowed.', 'us' ),
			'type' => 'textarea_raw_html',
			'std' => $config['atts']['marker_text'],
			'edit_field_class' => 'vc_col-sm-12 vc_column pretend_textfield',
			'weight' => 180,
		),
		array(
			'param_name' => 'height',
			'heading' => __( 'Map Height (pixels)', 'us' ),
			'description' => '',
			'type' => 'textfield',
			'std' => $config['atts']['height'],
			'weight' => 170,
		),
		array(
			'param_name' => 'type',
			'heading' => __( 'Map Type', 'us' ),
			'description' => '',
			'type' => 'dropdown',
			'value' => array(
				__( 'Roadmap', 'us' ) => 'roadmap',
				__( 'Roadmap + Terrain', 'us' ) => 'terrain',
				__( 'Satellite', 'us' ) => 'satellite',
				__( 'Satellite + Roadmap', 'us' ) => 'hybrid',
			),
			'std' => $config['atts']['type'],
			'edit_field_class' => 'vc_col-sm-6 vc_column',
			'weight' => 160,
		),
		array(
			'param_name' => 'zoom',
			'heading' => __( 'Map Zoom', 'us' ),
			'description' => '',
			'type' => 'dropdown',
			'value' => array(
				' 1' => '1',
				' 2' => '2',
				' 3' => '3',
				' 4' => '4',
				' 5' => '5',
				' 6' => '6',
				' 7' => '7',
				' 8' => '8',
				' 9' => '9',
				' 10' => '10',
				' 11' => '11',
				' 12' => '12',
				' 13' => '13',
				' 14' => '14',
				' 15' => '15',
				' 16' => '16',
				' 17' => '17',
				' 18' => '18',
				' 19' => '19',
				' 20' => '20',
			),
			'std' => $config['atts']['zoom'],
			'edit_field_class' => 'vc_col-sm-6 vc_column',
			'weight' => 150,
		),
		array(
			'param_name' => 'latitude',
			'heading' => __( 'Map Latitude (optional)', 'us' ),
			'description' => __( 'If Longitude and Latitude are set, they override the Address value.', 'us' ),
			'type' => 'textfield',
			'std' => $config['atts']['latitude'],
			'edit_field_class' => 'vc_col-sm-6 vc_column',
			'weight' => 140,
		),
		array(
			'param_name' => 'longitude',
			'heading' => __( 'Map Longitude (optional)', 'us' ),
			'description' => __( 'If Longitude and Latitude are set, they override the Address value.', 'us' ),
			'type' => 'textfield',
			'std' => $config['atts']['longitude'],
			'edit_field_class' => 'vc_col-sm-6 vc_column',
			'weight' => 130,
		),
		array(
			'param_name' => 'custom_marker_img',
			'heading' => __( 'Custom Marker Image', 'us' ),
			'description' => __( 'Image should NOT be bigger then 80x80 px', 'us' ),
			'type' => 'attach_image',
			'std' => $config['atts']['custom_marker_img'],
			'weight' => 120,
		),
		array(
			'param_name' => 'custom_marker_size',
			'heading' => __( 'Custom Marker Size', 'us' ),
			'description' => '',
			'type' => 'dropdown',
			'value' => array(
				'20x20' => '20',
				'30x30' => '30',
				'40x40' => '40',
				'50x50' => '50',
				'60x60' => '60',
				'70x70' => '70',
				'80x80' => '80',
			),
			'std' => $config['atts']['custom_marker_size'],
			'dependency' => array( 'element' => 'custom_marker_img', 'not_empty' => TRUE ),
			'weight' => 110,
		),
		array(
			'param_name' => 'add_markers',
			'heading' => __( 'Additional Markers', 'us' ),
			'description' => '',
			'type' => 'checkbox',
			'value' => array( __( 'Add more Markers to the map', 'us' ) => TRUE ),
			( ( $config['atts']['add_markers'] !== FALSE ) ? 'std' : '_std' ) => $config['atts']['add_markers'],
			'std' => $config['atts']['add_markers'],
			'weight' => 100,
		),
		array(
			'param_name' => 'marker2_address',
			'heading' => sprintf( __( 'Marker %d Address', 'us' ), 2 ),
			'description' => '',
			'type' => 'textfield',
			'std' => $config['atts']['marker2_address'],
			'dependency' => array( 'element' => 'add_markers', 'not_empty' => TRUE ),
			'weight' => 90,
		),
		array(
			'param_name' => 'marker2_text',
			'heading' => sprintf( __( 'Marker %d Text', 'us' ), 2 ),
			'description' => __( 'Enter your content, HTML tags are allowed.', 'us' ),
			'type' => 'textarea_raw_html',
			'std' => $config['atts']['marker2_text'],
			'edit_field_class' => 'vc_col-sm-12 vc_column pretend_textfield',
			'dependency' => array( 'element' => 'add_markers', 'not_empty' => TRUE ),
			'weight' => 80,
		),
		array(
			'param_name' => 'marker3_address',
			'heading' => sprintf( __( 'Marker %d Address', 'us' ), 3 ),
			'description' => '',
			'type' => 'textfield',
			'std' => $config['atts']['marker3_address'],
			'dependency' => array( 'element' => 'add_markers', 'not_empty' => TRUE ),
			'weight' => 70,
		),
		array(
			'param_name' => 'marker3_text',
			'heading' => sprintf( __( 'Marker %d Text', 'us' ), 3 ),
			'description' => __( 'Enter your content, HTML tags are allowed.', 'us' ),
			'type' => 'textarea_raw_html',
			'std' => $config['atts']['marker3_text'],
			'edit_field_class' => 'vc_col-sm-12 vc_column pretend_textfield',
			'dependency' => array( 'element' => 'add_markers', 'not_empty' => TRUE ),
			'weight' => 60,
		),
		array(
			'param_name' => 'marker4_address',
			'heading' => sprintf( __( 'Marker %d Address', 'us' ), 4 ),
			'description' => '',
			'type' => 'textfield',
			'std' => $config['atts']['marker4_address'],
			'dependency' => array( 'element' => 'add_markers', 'not_empty' => TRUE ),
			'weight' => 50,
		),
		array(
			'param_name' => 'marker4_text',
			'heading' => sprintf( __( 'Marker %d Text', 'us' ), 4 ),
			'description' => __( 'Enter your content, HTML tags are allowed.', 'us' ),
			'type' => 'textarea_raw_html',
			'std' => $config['atts']['marker4_text'],
			'edit_field_class' => 'vc_col-sm-12 vc_column pretend_textfield',
			'dependency' => array( 'element' => 'add_markers', 'not_empty' => TRUE ),
			'weight' => 40,
		),
		array(
			'param_name' => 'marker5_address',
			'heading' => sprintf( __( 'Marker %d Address', 'us' ), 5 ),
			'description' => '',
			'type' => 'textfield',
			'std' => $config['atts']['marker5_address'],
			'dependency' => array( 'element' => 'add_markers', 'not_empty' => TRUE ),
			'weight' => 30,
		),
		array(
			'param_name' => 'marker5_text',
			'heading' => sprintf( __( 'Marker %d Text', 'us' ), 5 ),
			'description' => __( 'Enter your content, HTML tags are allowed.', 'us' ),
			'type' => 'textarea_raw_html',
			'std' => $config['atts']['marker5_text'],
			'edit_field_class' => 'vc_col-sm-12 vc_column pretend_textfield',
			'dependency' => array( 'element' => 'add_markers', 'not_empty' => TRUE ),
			'weight' => 20,
		),
		array(
			'param_name' => 'el_class',
			'heading' => __( 'Extra class name', 'us' ),
			'description' => __( 'If you wish to style particular content element differently, then use this field to add a class name and then refer to it in your css file.', 'us' ),
			'type' => 'textfield',
			'std' => $config['atts']['el_class'],
			'weight' => 10,
		),
	),
) );
vc_remove_element( 'vc_gmaps' );
